# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]


jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Ensure runner has write permissions
      run: sudo chown -R $USER:$USER /home/ubuntu/app/actions-runner/_work/React-Redux-Login-Ecom-Project
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: sudo npm ci --force
    - run: |
        touch .env
        echo "${{secrets.PROD_ENV_VAR}}" > .env
    - name: Install PM2
      run: sudo npm install -g pm2
    - name: Start or Restart npm run dev with PM2
      run: |
        if pm2 list | grep -q "dev-app"; then
          sudo pm2 restart dev-app
        else
          sudo pm2 start npm --name "dev-app" -- run dev
        fi

    - name: Start or Restart server.js with PM2
      run: |
        if pm2 list | grep -q "server-app"; then
          sudo pm2 restart server-app
        else
          sudo pm2 start node server.js --name "server-app" --cwd ./server
        fi

    - name: Display PM2 list
      run: sudo pm2 list